apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: web
spec:
  type: NodePort
  selector:
    app: web1
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080

# docker run -d -p 8080:80 nginx      