# Code Generated by Sidekick is for learning and experimentation purposes only.
from azure.identity import DefaultAzureCredential
from azure.mgmt.resource import ResourceManagementClient

# Set your Azure subscription ID and tag key-value pair
subscription_id = 'your-subscription-id'
tag_key = 'tag1'
tag_value = 'value1'

# Authenticate using Azure SDK
credential = DefaultAzureCredential()
resource_client = ResourceManagementClient(credential, subscription_id)

# Find all resources with the specified tag
resources = resource_client.resources.list(filter=f"tagName eq '{tag_key}' and tagValue eq '{tag_value}'")

# Delete each resource
for resource in resources:
    print(f'Deleting resource: {resource.id}')
    resource_client.resources.begin_delete_by_id(resource.id, api_version='2021-04-01')

print('All resources with the specified tags have been deleted.')
