# Code Generated by Sidekick is for learning and experimentation purposes only.

# ListVnetsAndUpload.ps1

# Step 1: Authenticate to Azure
az login

# Step 2: List Vnets and Subnets
$vnetData = az network vnet list --query "[].{Name:name, Subnets:subnets}" --output json

# Step 3: Convert JSON to CSV
$vnetData | ConvertFrom-Json | Export-Csv -Path "YourName_sub_Vnet.csv" -NoTypeInformation

# Step 4: Get the connection string using Azure CLI
$connectionString = az storage account show-connection-string --name "mystorageaccount" --resource-group "myresourcegroup" --output tsv

# Step 5: Upload CSV to Azure Blob Storage
# Define variables for storage account and container
$storageAccountName = "mystorageaccount"
$containerName = "yourcontainer"

# Upload the CSV file to the container
az storage blob upload --account-name $storageAccountName --container-name $containerName --name "YourName_sub_Vnet.csv" --file "YourName_sub_Vnet.csv" --connection-string $connectionString
