# SPDX-License-Identifier: MIT-0
# tasks file for nginx_install
---
- name: Update the system package cache
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy index.html to Nginx path
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: '0644'
  notify: restart nginx
