apiVersion: v1
kind: Namespace
metadata:
  name: sidecar
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  namespace: sidecar
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  - name: sidecar
    image: busybox:1.28
    command: ["/bin/sh", "-c", "tail -F /var/log/nginx/access.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  volumes:
  - name: shared-logs
    emptyDir: {}
