version: "3.8"
services:
  webapp:
    image: docker.io/riteshzode/flaskapp:v2 # Replace with image version v1, v2, v3
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - webapp_data:/usr/src/app
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  webapp_data:
  redis_data:

networks:
  app_network: