version: "3.8"
services:
  webapp:
    image: docker.io/riteshzode/flaskapp:v1 # Replace with image version v1, v2, v3
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"