#SPDX-License-Identifier: MIT-0
# tasks file for create_ec2
---
- name: Launching AWS instance using Ansible
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    security_groups: "{{ security_groups }}"
    count: "{{ count }}"
    wait: yes
    assign_public_ip: "{{ assign_public_ip }}"
    tags:
      Name: "{{ tag_name }}"
  register: ec2

- name: Output the public IP address
  debug:
    msg: "Public IP: {{ ec2.instances[0].public_ip_address }}"

- name: Add the new EC2 instance to Ansible inventory
  add_host:
    name: "{{ ec2.instances[0].public_ip_address }}"
    groups: launched


- name: Update inventory file with new instance IP, key, and user
  lineinfile:
    path: "{{ hosts_file_path }}"
    line: "{{ item.public_ip_address }} {{ key_file_path }} {{ ansible_user }}"
    create: yes
    insertafter: EOF
  loop: "{{ ec2.instances }}"

- name: Wait for 3 minutes to allow the instance to initialize
  wait_for:
    timeout: "{{ wait_timeout }}"
