version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - data:/usr/share/nginx/html
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge